### ISSUE TITLE
item edit can't drag and things into block !(bukkit 1.13.2)

### ISSUE THREAD

**Issue by rayyuan5010** [caliog/Rolecraft#11]
/item edit  
can't drag any things 

(bukkit 1.13.2)

**Comment by caliog** [comment]
Latest version of Rolecraft ? Any errors in the server log ? Are you using spigot or craftbukkit?

**Comment by rayyuan5010** [comment]
download from https://dev.bukkit.org/projects/rolecraft  
no error in server log 
useing craftbukkit 1.13.2

**Comment by caliog** [comment]
Yes but make sure you are using v3.2.19 cause this is a known bug in lower versions.
I will doublecheck if it works for me.

EDIT: I just noticed I read 1.13.1 all the time now I see you wrote 1.13.2, my bad ! Plugin may not be compatible with 1.13.2 especially if you are using craftbukkit. Next update should fix this.

**Comment by caliog** [comment]
I tested the plugin with 1.13.2. It works with spigot but not with craftbukkit. I will fix it in the next update, but you make it work by using spigot, too.

**Comment by rayyuan5010** [comment]
Ok! Thx a lot !

**Comment by rayyuan5010** [comment]
and another question i create mob like 

```
name: abc
entity-type: ZOMBIE
level: 9
hitpoints: 75
defense: 29
damage: 1
aggressive: true
pet: false
experience: 39%9-10
extra-spawn-time: 0
equipment:
  leggings: DIAMOND_LEGGINGS
  helmet: DIAMOND_HELMET
  chestplate: DIAMOND_CHESTPLATE
  boots: DIAMOND_BOOTS
  hand: DIAMOND_SWORD
```

but i use /msz create abc 10 10 still tell me abc is not a mob 

% i change to spigot 1.13.2
